### ISSUE TITLE
relacionamento curriculo profile

### ISSUE THREAD

**Issue by denissonleal** [genivalrm/recruitment-platform#35]
Pq a decisao de salvar um array com os curriculos no profile ao invés de salvar o id do profile no curriculo?

**Comment by genivalrm** [comment]
Pelo fato do profile poder ter vários currículos.

**Comment by denissonleal** [comment]
exatamente, o relacionamento ta invertido

**Comment by genivalrm** [comment]
Corrigido, relacionamento foi mudado.
